from __future__ import annotations

EMERGENCIES: dict[str, dict] = {
    "heart-attack": {
        "id": "heart-attack",
        "title": "Heart Attack",
        "summary": "Possible myocardial infarction — act fast.",
        "immediate_steps": [
            "Call emergency services immediately",
            "Have the person sit or lie comfortably, loosen tight clothing",
            "If prescribed and conscious, they may take their nitroglycerin as directed",
            "If trained and advised by emergency dispatch, aspirin may be considered unless allergic",
            "Be ready to start CPR if the person becomes unresponsive and not breathing normally",
        ],
        "do_not": [
            "Do not drive yourself if symptoms are severe",
            "Do not ignore chest pressure with jaw/arm pain or shortness of breath",
            "Do not give medications not prescribed without guidance",
        ],
        "call_emergency": True,
        "visual_guide": ["Recognize symptoms", "Call emergency", "Rest + monitor", "CPR if needed"],
    },
    "stroke": {
        "id": "stroke",
        "title": "Stroke",
        "summary": "FAST: Face drooping, Arm weakness, Speech difficulty, Time to call.",
        "immediate_steps": [
            "Call emergency services immediately",
            "Note the time symptoms started",
            "Keep the person safe and still; do not give food or drink",
            "If unconscious, recovery position if breathing; CPR if not breathing normally",
        ],
        "do_not": [
            "Do not wait to see if symptoms pass",
            "Do not give blood thinners or medications unless instructed",
        ],
        "call_emergency": True,
        "visual_guide": ["FAST check", "Call now", "Note onset time", "Hospital"],
    },
    "snake-bite": {
        "id": "snake-bite",
        "title": "Snake Bite",
        "summary": "Immobilize and get emergency care; antivenom may be needed.",
        "immediate_steps": [
            "Move away from the snake; call emergency services",
            "Keep the bitten area still and below heart level if possible",
            "Remove rings/tight items near the bite",
            "Wash gently with soap and water if available",
            "Get to hospital for evaluation",
        ],
        "do_not": [
            "Do not cut the wound or try to suck venom",
            "Do not apply ice or a tight tourniquet",
            "Do not try to catch the snake",
        ],
        "call_emergency": True,
        "visual_guide": ["Safety first", "Immobilize", "Call emergency", "Hospital"],
    },
    "dog-bite": {
        "id": "dog-bite",
        "title": "Dog Bite",
        "summary": "Clean wound and assess rabies/tetanus risk.",
        "immediate_steps": [
            "Wash with soap and running water for several minutes",
            "Apply gentle pressure for bleeding",
            "Cover with clean bandage",
            "Seek medical care for deep wounds, face bites, or unknown vaccination status",
        ],
        "do_not": ["Do not ignore signs of infection", "Do not delay rabies evaluation when indicated"],
        "call_emergency": False,
        "visual_guide": ["Wash", "Control bleeding", "Bandage", "Seek care"],
    },
    "bee-sting": {
        "id": "bee-sting",
        "title": "Bee Sting",
        "summary": "Remove stinger; watch for anaphylaxis.",
        "immediate_steps": [
            "Remove stinger by scraping (not squeezing) if present",
            "Wash area, cool compress, oral antihistamine if appropriate",
            "If anaphylaxis (trouble breathing, swelling of lips/tongue, collapse): use epinephrine if prescribed and call emergency",
        ],
        "do_not": ["Do not squeeze the stinger sac", "Do not ignore breathing difficulty"],
        "call_emergency": False,
        "visual_guide": ["Remove stinger", "Cool compress", "Watch allergy", "ER if severe"],
    },
    "poison": {
        "id": "poison",
        "title": "Poisoning",
        "summary": "Call poison control / emergency; do not induce vomiting unless told.",
        "immediate_steps": [
            "Call local poison control or emergency services",
            "If safe, move to fresh air for inhaled toxins",
            "Bring the container/label if going to hospital",
            "Follow dispatcher instructions exactly",
        ],
        "do_not": [
            "Do not induce vomiting unless instructed",
            "Do not give fluids/food unless instructed",
        ],
        "call_emergency": True,
        "visual_guide": ["Identify substance", "Call poison control", "Follow advice", "ER"],
    },
    "burns": {
        "id": "burns",
        "title": "Burns",
        "summary": "Cool with water; cover; escalate for large/chemical/electrical burns.",
        "immediate_steps": [
            "Cool under cool running water for 20 minutes (not ice)",
            "Remove tight items near burn if not stuck",
            "Cover loosely with clean non-stick dressing",
            "Seek emergency care for large, facial, airway, chemical, or electrical burns",
        ],
        "do_not": ["Do not apply butter/oils", "Do not burst blisters", "Do not use ice directly"],
        "call_emergency": False,
        "visual_guide": ["Cool water", "Cover", "Pain care", "ER if severe"],
    },
    "electric-shock": {
        "id": "electric-shock",
        "title": "Electric Shock",
        "summary": "Ensure power is off before touching the person.",
        "immediate_steps": [
            "Shut off power / separate with non-conductive object if trained and safe",
            "Call emergency services",
            "Check breathing and pulse; start CPR if needed",
            "Treat burns after scene is safe",
        ],
        "do_not": ["Do not touch the person while they are still in contact with electricity"],
        "call_emergency": True,
        "visual_guide": ["Power off", "Call emergency", "CPR if needed", "Hospital"],
    },
    "cpr": {
        "id": "cpr",
        "title": "CPR",
        "summary": "Hands-only CPR: push hard and fast in the center of the chest.",
        "immediate_steps": [
            "Call emergency / put phone on speaker",
            "Place heel of hand on center of chest; interlock hands",
            "Compress at least 5 cm deep at 100–120/min",
            "Use AED as soon as available and follow prompts",
        ],
        "do_not": ["Do not delay compressions for prolonged pulse checks"],
        "call_emergency": True,
        "visual_guide": ["Check response", "Call", "Compress", "AED"],
    },
    "choking": {
        "id": "choking",
        "title": "Choking",
        "summary": "Encourage coughing; abdominal thrusts if severe obstruction.",
        "immediate_steps": [
            "Ask: Are you choking? If they cannot speak/cough/breathe, act",
            "Deliver abdominal thrusts (Heimlich) if trained; back blows for infants per guidelines",
            "Call emergency if obstruction persists or person becomes unresponsive",
            "Start CPR if unresponsive",
        ],
        "do_not": ["Do not perform blind finger sweeps"],
        "call_emergency": True,
        "visual_guide": ["Assess", "Back blows / thrusts", "Call", "CPR if needed"],
    },
    "broken-bone": {
        "id": "broken-bone",
        "title": "Broken Bone",
        "summary": "Immobilize and seek care; open fractures need emergency attention.",
        "immediate_steps": [
            "Keep the injured limb still",
            "Control bleeding with clean pressure if present",
            "Ice wrapped in cloth for swelling",
            "Seek urgent care/ER for deformity, open wound, numbness, or severe pain",
        ],
        "do_not": ["Do not try to realign the bone", "Do not move if spinal injury suspected"],
        "call_emergency": False,
        "visual_guide": ["Immobilize", "Ice", "Elevate if safe", "Medical care"],
    },
    "bleeding": {
        "id": "bleeding",
        "title": "Bleeding",
        "summary": "Apply firm direct pressure; escalate for severe hemorrhage.",
        "immediate_steps": [
            "Apply firm direct pressure with clean cloth",
            "Add more dressing if soaked — do not remove the first layer",
            "Elevate if possible and no fracture suspected",
            "Call emergency for spurting blood, amputation, or signs of shock",
        ],
        "do_not": ["Do not use a tourniquet unless trained and bleeding is life-threatening"],
        "call_emergency": False,
        "visual_guide": ["Pressure", "Dressing", "Elevate", "ER if severe"],
    },
    "animal-bites": {
        "id": "animal-bites",
        "title": "Animal Bites",
        "summary": "Clean thoroughly; evaluate infection and rabies risk.",
        "immediate_steps": [
            "Wash with soap and water",
            "Control bleeding",
            "Seek care for puncture wounds, deep bites, or immunocompromise",
            "Report bites per local public health rules when required",
        ],
        "do_not": ["Do not ignore fever or spreading redness"],
        "call_emergency": False,
        "visual_guide": ["Wash", "Bandage", "Tetanus/rabies check", "Follow-up"],
    },
    "chemical-burns": {
        "id": "chemical-burns",
        "title": "Chemical Burns",
        "summary": "Remove chemical and flush with water for extended time.",
        "immediate_steps": [
            "Remove contaminated clothing carefully",
            "Flush with cool running water for 20+ minutes",
            "Call poison control / emergency",
            "Bring chemical label to hospital if safe",
        ],
        "do_not": ["Do not neutralize with other chemicals", "Do not apply ointments before flushing"],
        "call_emergency": True,
        "visual_guide": ["Remove chemical", "Flush", "Call", "ER"],
    },
    "heat-stroke": {
        "id": "heat-stroke",
        "title": "Heat Stroke",
        "summary": "Medical emergency — cool rapidly and call emergency services.",
        "immediate_steps": [
            "Call emergency services",
            "Move to shade/cool area",
            "Remove excess clothing; cool with water and fanning",
            "Do not force oral fluids if altered mental status",
        ],
        "do_not": ["Do not leave the person alone", "Do not use alcohol rubs"],
        "call_emergency": True,
        "visual_guide": ["Call", "Cool environment", "Active cooling", "Hospital"],
    },
    "hypothermia": {
        "id": "hypothermia",
        "title": "Hypothermia",
        "summary": "Gentle rewarming; emergency care for severe cases.",
        "immediate_steps": [
            "Move to warm environment; handle gently",
            "Remove wet clothing; insulate with blankets",
            "Warm sweet drinks only if fully conscious",
            "Call emergency for confusion, severe shivering stop, or unresponsiveness",
        ],
        "do_not": ["Do not rub vigorously", "Do not use direct high heat"],
        "call_emergency": True,
        "visual_guide": ["Shelter", "Dry + insulate", "Warm gradually", "ER if severe"],
    },
}


POPULAR_CONDITIONS = [
    {"id": "fever", "name": "Fever", "query": "I have fever"},
    {"id": "cold", "name": "Cold", "query": "I have a common cold"},
    {"id": "flu", "name": "Flu", "query": "I think I have the flu"},
    {"id": "covid", "name": "COVID", "query": "Possible COVID symptoms"},
    {"id": "food-poisoning", "name": "Food Poisoning", "query": "Food poisoning symptoms"},
    {"id": "head-injury", "name": "Head Injury", "query": "I had a head injury"},
    {"id": "bleeding", "name": "Bleeding", "query": "I am bleeding"},
    {"id": "broken-bone", "name": "Broken Bone", "query": "Possible broken bone"},
    {"id": "eye-infection", "name": "Eye Infection", "query": "Eye infection symptoms"},
    {"id": "ear-infection", "name": "Ear Infection", "query": "Ear infection pain"},
    {"id": "tooth-pain", "name": "Tooth Pain", "query": "Severe tooth pain"},
]

BODY_REGIONS = {
    "head": ["Headache", "Dizziness", "Confusion"],
    "eye": ["Red eye", "Vision changes", "Eye pain"],
    "ear": ["Ear pain", "Hearing loss", "Discharge"],
    "chest": ["Chest pain", "Shortness of breath", "Palpitations"],
    "arm": ["Arm pain", "Numbness", "Swelling"],
    "leg": ["Leg pain", "Swelling", "Calf tenderness"],
    "neck": ["Neck pain", "Stiffness", "Swollen glands"],
    "back": ["Back pain", "Sciatica", "Muscle spasm"],
    "abdomen": ["Abdominal pain", "Nausea", "Diarrhea"],
    "skin": ["Rash", "Itching", "Lesion"],
}
